<def f='llvm/llvm/include/llvm/Support/Error.h' l='1191' type='llvm::Error llvm::FileError::takeError()'/>
<use f='llvm/llvm/unittests/Support/ErrorTest.cpp' l='891' u='c' c='_ZN12_GLOBAL__N_124Error_FileErrorTest_Test8TestBodyEv'/>
