<dec f='llvm/llvm/tools/llvm-xray/xray-account.h' l='78' type='bool llvm::xray::LatencyAccountant::accountRecord(const llvm::xray::XRayRecord &amp; Record)'/>
<def f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='136' ll='219' type='bool llvm::xray::LatencyAccountant::accountRecord(const llvm::xray::XRayRecord &amp; Record)'/>
<use f='llvm/llvm/tools/llvm-xray/xray-account.cpp' l='444' u='c'/>
<doc f='llvm/llvm/tools/llvm-xray/xray-account.h' l='69'>/// Returns false in case we fail to account the provided record. This happens
  /// in the following cases:
  ///
  ///   - An exit record does not match any entry records for the same function.
  ///     If we&apos;ve been set to deduce sibling calls, we try walking up the stack
  ///     and recording times for the higher level functions.
  ///   - A record has a TSC that&apos;s before the latest TSC that has been
  ///     recorded. We still record the TSC for the min-max.
  ///</doc>
